### ISSUE TITLE
Encounter problems when installing the scalpel

### ISSUE THREAD

**Issue by Jacob-yen** [SMAT-Lab/Scalpel#90]
Hi~ 
Thanks for sharing the fantastic toolkit, Scalpel!
I met a problem when I tried to install the Scalpel. I had both tried the installation through `python3 -m pip install git+https://github.com/SMAT-Lab/Scalpel.git` and `python -m pip install .` and got the same error message as below:

```
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/SMAT-Lab/Scalpel.git
  Cloning https://github.com/SMAT-Lab/Scalpel.git to /tmp/pip-req-build-_chbey86
  Running command git clone -q https://github.com/SMAT-Lab/Scalpel.git /tmp/pip-req-build-_chbey86
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/cli/req_command.py", line 199, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/commands/install.py", line 318, in run
    requirement_set = resolver.resolve(
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 103, in resolve
    r = self.factory.make_requirement_from_install_req(
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 429, in make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 200, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 306, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 151, in __init__
    self.dist = self._prepare()
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 234, in _prepare
    dist = self._prepare_distribution()
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 317, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/operations/prepare.py", line 570, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/operations/prepare.py", line 60, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/distributions/sdist.py", line 29, in prepare_distribution_metadata
    self.req.load_pyproject_toml()
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/req/req_install.py", line 493, in load_pyproject_toml
    pyproject_toml_data = load_pyproject_toml(
  File "/usr/local/lib/python3.8/dist-packages/pip/_internal/pyproject.py", line 62, in load_pyproject_toml
    pp_toml = toml.load(f)
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/toml/decoder.py", line 156, in load
    return loads(f.read(), _dict, decoder)
  File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/toml/decoder.py", line 340, in loads
    raise TomlDecodeError("Unbalanced quotes", original, i)
pip._vendor.toml.decoder.TomlDecodeError: Unbalanced quotes (line 7 column 30 char 183
```

Looking forward to receiving your reply, and thanks in advance!

**Comment by Jarvx** [comment]
Hi,

thank you for your interest in this project. Can you try to use the pip command to get it installed? Please let me any issues you encounter. 

pip install python-scalpel
